"""Map Pydantic AI streaming events into Conductor event payloads.

This module holds the bridge between Pydantic AI's event stream and
Conductor's ``EventCallback`` payloads.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from typing import Any

from pydantic_ai import Agent
from pydantic_ai.messages import (
    FunctionToolCallEvent,
    FunctionToolResultEvent,
    PartDeltaEvent,
    PartStartEvent,
    TextPart,
    TextPartDelta,
    ThinkingPart,
    ThinkingPartDelta,
    ToolCallPart,
)

from conductor.mcp.manager import FS_HINT, GENERIC_HINT, TRUNCATION_MARKER_PREFIX
from conductor.providers._event_format import (
    extract_tool_result_text,
    format_tool_arguments,
)

EventCallback = Callable[[str, dict[str, Any]], None]

logger = logging.getLogger(__name__)


def _parse_truncation_marker(result: Any) -> dict[str, Any] | None:
    """Parse truncation metadata from the marker appended to a result.

    Mirrors ``ClaudeProvider._parse_truncation_marker`` so that Pydantic AI
    tool results can emit ``agent_tool_output_truncated`` with the same
    payload shape. The marker is generated by ``MCPManager._maybe_truncate_response``
    and always has the form::

        [output truncated: {original} chars -> {kept} kept{; optional path}. {HINT}]

    Args:
        result: The possibly truncated tool result. Non-string values are ignored.

    Returns:
        A dict with ``original_chars``, ``kept_chars``, and ``spill_path``
        (``None`` when the marker omits a path), or ``None`` when the
        result is not truncated.
    """
    if not isinstance(result, str) or not result:
        return None

    tail_window = 8192
    if TRUNCATION_MARKER_PREFIX not in result[-tail_window:]:
        return None

    tail = result[-tail_window:]
    match = re.search(
        r".*"
        + re.escape(TRUNCATION_MARKER_PREFIX)
        + r"\s*(\d+)\s*chars\s*->\s*(\d+)\s*kept"
        + r"(?:;\s*full output saved to:\s*(.+?))?\."
        + r"\s*"
        + r"(?:"
        + re.escape(GENERIC_HINT)
        + r"|"
        + re.escape(FS_HINT)
        + r")"
        + r"\]\s*$",
        tail,
        re.DOTALL,
    )

    if not match:
        return None

    original_chars = int(match.group(1))
    kept_chars = int(match.group(2))
    spill_path = match.group(3).strip() if match.group(3) else None

    return {
        "original_chars": original_chars,
        "kept_chars": kept_chars,
        "spill_path": spill_path,
    }


def _extract_tool_call_args(call: ToolCallPart) -> dict[str, Any] | None:
    """Return tool-call arguments as a dict, or None if empty/absent."""
    args = call.args_as_dict() if call.args else None
    if not args:
        return None
    return args


def map_pydantic_event(
    agent: Agent[Any, Any],
    event: Any,
) -> tuple[str, dict[str, Any]] | None:
    """Translate a Pydantic AI event into a Conductor event tuple.

    Handles streaming model-response events (``PartStartEvent`` for full
    parts, ``PartDeltaEvent`` for deltas) and response-handling tool events
    (``FunctionToolCallEvent`` / ``FunctionToolResultEvent``). ``agent_name``
    is derived from the Pydantic AI agent's configured ``name`` so the
    downstream ``EventCallback`` receives the same shape used by the other
    providers.

    Args:
        agent: The Pydantic AI agent that produced the event. Its ``name`` is
            used for the ``agent_name`` payload key.
        event: A Pydantic AI event (``AgentStreamEvent`` or
            ``HandleResponseEvent``).

    Returns:
        A tuple ``(event_type, data_dict)`` for Conductor, or ``None`` if
        the event should be ignored.
    """
    agent_name = agent.name or "agent"

    if isinstance(event, PartStartEvent):
        part = event.part
        if isinstance(part, TextPart) and part.content:
            return ("agent_message", {"agent_name": agent_name, "content": part.content})
        if isinstance(part, ThinkingPart) and part.content:
            return ("agent_reasoning", {"agent_name": agent_name, "content": part.content})
        if isinstance(part, ToolCallPart):
            return (
                "agent_tool_start",
                {
                    "agent_name": agent_name,
                    "tool_name": part.tool_name,
                    "arguments": format_tool_arguments(_extract_tool_call_args(part)),
                },
            )
        return None

    if isinstance(event, PartDeltaEvent):
        delta = event.delta
        if isinstance(delta, TextPartDelta) and delta.content_delta:
            return ("agent_message", {"agent_name": agent_name, "content": delta.content_delta})
        if isinstance(delta, ThinkingPartDelta) and delta.content_delta:
            return ("agent_reasoning", {"agent_name": agent_name, "content": delta.content_delta})
        return None

    if isinstance(event, FunctionToolCallEvent):
        call = event.part
        return (
            "agent_tool_start",
            {
                "agent_name": agent_name,
                "tool_name": call.tool_name,
                "arguments": format_tool_arguments(_extract_tool_call_args(call)),
            },
        )

    if isinstance(event, FunctionToolResultEvent):
        call = event.part
        result_text = extract_tool_result_text(call.content)
        return (
            "agent_tool_complete",
            {
                "agent_name": agent_name,
                "tool_name": call.tool_name,
                "result": result_text,
            },
        )

    return None


def emit_pydantic_event(
    agent: Agent[Any, Any],
    event: Any,
    event_callback: EventCallback | None,
) -> None:
    """Map a Pydantic AI event and emit it through a Conductor callback.

    Callback errors are swallowed with a debug log so subscribers can never
    crash the agent loop.

    Args:
        agent: The Pydantic AI agent that produced the event.
        event: A Pydantic AI event to map and forward.
        event_callback: Optional Conductor event callback. If ``None``, the
            event is silently dropped.
    """
    if event_callback is None:
        return

    mapped = map_pydantic_event(agent, event)
    if mapped is None:
        return

    event_type, data = mapped
    try:
        event_callback(event_type, data)
    except Exception:
        logger.debug("Error in event_callback for %s", event_type, exc_info=True)


def emit_agent_turn_start(
    event_callback: EventCallback | None,
    turn: int | str,
) -> None:
    """Emit an ``agent_turn_start`` event, swallowing callback errors.

    Conductor expects ``{"turn": "awaiting_model"}`` immediately before
    each model API call and ``{"turn": N}`` at the start of each agentic-loop
    iteration. This helper lets the provider loop drive both without
    duplicating the error-swallowing logic.

    Args:
        event_callback: Optional Conductor event callback. If ``None``, the
            event is silently dropped.
        turn: Either the integer iteration number or the string
            ``"awaiting_model"``.
    """
    if event_callback is None:
        return

    try:
        event_callback("agent_turn_start", {"turn": turn})
    except Exception:
        logger.debug("Error in event_callback for agent_turn_start", exc_info=True)


def maybe_emit_tool_truncation(
    agent: Agent[Any, Any],
    tool_name: str,
    result: Any,
    event_callback: EventCallback | None,
) -> None:
    """Emit ``agent_tool_output_truncated`` if a tool result is truncated.

    ``MCPManager`` appends a plain-text marker to oversized results, but the
    Pydantic AI adapter does not parse it. This helper detects the marker and
    forwards the structured truncation event to subscribers with the same
    payload keys used by ``ClaudeProvider``.

    Args:
        agent: The Pydantic AI agent that produced the tool result.
        tool_name: Name of the tool whose output was truncated.
        result: The raw tool result string returned by the tool call.
        event_callback: Optional Conductor event callback. If ``None``, the
            check is skipped.
    """
    if event_callback is None:
        return

    truncation_info = _parse_truncation_marker(result)
    if truncation_info is None:
        return

    agent_name = agent.name or "agent"
    try:
        event_callback(
            "agent_tool_output_truncated",
            {
                "agent_name": agent_name,
                "tool_name": tool_name,
                "original_chars": truncation_info["original_chars"],
                "kept_chars": truncation_info["kept_chars"],
                "spill_path": truncation_info["spill_path"],
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_tool_output_truncated", exc_info=True)
